version: '3.8'

services:
  redis:
    image: redis:7.4.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - REDIS_ADDR=redis:6379
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SENDER_EMAIL=noreply@example.com
      - ALLOW_UNENCRYPTED=true
    depends_on:
      - redis
      - mailhog
    volumes:
      - ./.env:/app/.env:ro

volumes:
  redis_data: